project_id = "cfkipvshbozcofsbpfln"

[functions.ai-route-planner]
verify_jwt = false

[functions.create-driver-account]
verify_jwt = false

[functions.create-employee]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false

[functions.public-register]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
