// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-routes.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-routes.ts
var list_routes_default = defineTool({
  name: "list_routes",
  title: "List bus lines",
  description: "List school bus lines (number, name, school, status) visible to the signed-in user.",
  inputSchema: {
    search: z.string().trim().optional().describe("Optional text to match in the line name."),
    limit: z.number().int().min(1).max(200).default(50).describe("Maximum lines to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    let q = supabaseForUser(ctx).from("routes").select("id, name, route_number, is_active, schools(name)").order("route_number", { ascending: true }).limit(limit);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    const routes = (data ?? []).map((r) => ({
      id: String(r.id),
      route_number: r.route_number ?? null,
      name: String(r.name ?? ""),
      is_active: Boolean(r.is_active),
      school: r.schools?.name ?? null
    }));
    return { content: [{ type: "text", text: JSON.stringify(routes) }], structuredContent: { routes } };
  }
});

// src/lib/mcp/tools/list-active-trips.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.4";
var list_active_trips_default = defineTool2({
  name: "list_active_trips",
  title: "List active trips",
  description: "List bus trips currently in progress with their line and last known location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("live_trips").select("id, route_id, started_at, current_latitude, current_longitude, last_location_update, routes(name, route_number)").eq("status", "in_progress").order("started_at", { ascending: false });
    if (error) throw new ToolError2(error.message);
    const trips = (data ?? []).map((t) => ({
      id: String(t.id),
      route_id: String(t.route_id),
      line: t.routes ? `#${t.routes.route_number ?? ""} ${t.routes.name ?? ""}`.trim() : null,
      started_at: t.started_at ?? null,
      latitude: t.current_latitude ?? null,
      longitude: t.current_longitude ?? null,
      last_location_update: t.last_location_update ?? null
    }));
    return { content: [{ type: "text", text: JSON.stringify(trips) }], structuredContent: { trips } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cfkipvshbozcofsbpfln";
var mcp_default = defineMcp({
  name: "seater-dashboard",
  title: "Seater Dashboard",
  version: "0.1.0",
  instructions: "Read-only tools for Seater school bus operations. Use `list_routes` to find bus lines and `list_active_trips` to see buses currently on the road. Results respect the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_routes_default, list_active_trips_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
